Traceback (most recent call last):
  File "./master.py", line 207, in <module>
    main(debug)
  File "./master.py", line 188, in main
    handler = ClientHandler(pid, address, port, process)
  File "./master.py", line 24, in __init__
    self.sock.connect((address, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
Exception in thread Thread-1 (most likely raised during interpreter shutdown):